version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: xinde-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+00:00'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phpxxxd
      MYSQL_USER: phpsql
      MYSQL_PASSWORD: bserp
      TZ: "UTC"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    # build: . 表示使用当前目录下的 Dockerfile 来构建 Go 应用的镜像
    build: .
    container_name: xinde-api-server
    restart: unless-stopped
    # 端口映射: 将主机的 8080 端口映射到容器的 8080 端口
    ports:
      - "8080:8080"
    # depends_on 确保数据库服务先于应用服务启动
    depends_on:
      - db
    # 卷挂载
    volumes:
      # 将你本机的配置文件挂载到容器内部
      - ./configs/config.yaml:/app/configs/config.yaml:ro # :ro 表示只读挂载，更安全
      # 为附件上传创建一个持久化存储目录
      - ./uploads:/app/uploads
    # 环境变量
    environment:
      # GIN_MODE: release # 部署时可以设为 release
      # 设置容器时区为东八区，这样 Go 的 time.Now() 默认就是东八区时间
      TZ: "Asia/Shanghai"

volumes:
  mysql-data:
