// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account/login": {
            "post": {
                "description": "用户登录，返回JWT token和用户基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.LoginResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/account/register": {
            "post": {
                "description": "用户名，真实姓名，公司名称，公司地址（可选），密码，手机号，邮箱（可选）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "注册一个新用户",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/approval/list": {
            "get": {
                "description": "根据前端传来的字段，返回对应的待审批列表/已同意申请/已拒绝申请的用户列表，根据创建时间降序排列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "管理员查看用户审批列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数，可选，默认为1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页的内容数量，可选，默认为设置的默认值",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.ApprovalListResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/approval/{id}": {
            "post": {
                "description": "批准用户申请，管理员决定是否同意用户的注册申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "批准用户申请",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.ApproveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "审批成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.ApproveResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "access_token有错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "没有该用户",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "409": {
                        "description": "用户已经被审批",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/list": {
            "get": {
                "description": "返回已被通过注册申请的用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "管理员查看用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数，可选，默认为1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页的内容数量，可选，默认为设置的默认值",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.ListResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/password/{id}": {
            "patch": {
                "description": "管理员根据用户ID修改用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "UpdatePassword　Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.UpdatePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改密码成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "access_token有错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "没有该用户",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/remark/{id}": {
            "patch": {
                "description": "管理员根据用户ID修改用户的备注信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "修改备注",
                "parameters": [
                    {
                        "description": "ResetRemark　Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.ResetRemarkReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改备注成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "access_token有错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "没有该用户",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/reset/password/{id}": {
            "post": {
                "description": "管理员根据用户ID重置用户的密码为123456",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "重置用户密码",
                "responses": {
                    "200": {
                        "description": "重置密码成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "access_token有错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "没有该用户",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/{id}": {
            "delete": {
                "description": "根据ID删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "删除用户",
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "access_token有错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "没有该用户",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/attachment/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据筛选条件分页获取已上传的附件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attachment"
                ],
                "summary": "获取附件列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "业务类型 (e.g., price_import)",
                        "name": "business_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件名 (模糊搜索)",
                        "name": "filename",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回附件列表",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_attachment.ListResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Token错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/attachments/{id}/download": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据附件ID下载对应的文件",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Attachment"
                ],
                "summary": "下载附件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "附件 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件流",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Token错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "附件或文件不存在",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/company/list": {
            "get": {
                "description": "返回所有的公司信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "管理员查看公司列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数，可选，默认为1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页的内容数量，可选，默认为设置的默认值",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_company.ListResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "token错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/company/price/level/{id}": {
            "patch": {
                "description": "管理员根据公司ID修改公司的价格等级",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "修改价格等级",
                "parameters": [
                    {
                        "description": "UpdatePriceLevel　Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_company.UpdatePriceLevelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改价格等级成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "access_token有错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "404": {
                        "description": "没有该公司",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/price/list": {
            "get": {
                "description": "返回所有产品的价格信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Price"
                ],
                "summary": "管理员查看价格列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数，可选，默认为1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "一页的内容数量，可选，默认为设置的默认值",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_price.ListResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "token错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/prices/import": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传一个包含价格信息的Excel文件，系统将解析文件内容并批量更新或插入价格数据。如果产品编码已存在，则会用新数据覆盖。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Price"
                ],
                "summary": "导入价格Excel文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "要上传的Excel文件 (格式: .xlsx)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "400": {
                        "description": "文件上传失败或文件内容/格式错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "Token错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "403": {
                        "description": "没有管理员权限",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "xinde_internal_dto_account.ApprovalListData": {
            "type": "object",
            "properties": {
                "company_name": {
                    "type": "string",
                    "example": "宁波鲍斯产业链服务有限公司"
                },
                "created_at": {
                    "type": "string",
                    "example": "2020-09-08 09:08:09"
                },
                "email": {
                    "type": "string",
                    "example": "13800138000@qq.com"
                },
                "id": {
                    "type": "integer",
                    "example": 2
                },
                "name": {
                    "type": "string",
                    "example": "张三，真实名称"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                },
                "username": {
                    "type": "string",
                    "example": "张三，账号名称"
                },
                "why": {
                    "type": "string",
                    "example": "同意该用户的申请；拒绝该用户的申请"
                }
            }
        },
        "xinde_internal_dto_account.ApprovalListPageData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xinde_internal_dto_account.ApprovalListData"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "pages": {
                    "type": "integer",
                    "example": 7
                },
                "total": {
                    "type": "integer",
                    "example": 137
                }
            }
        },
        "xinde_internal_dto_account.ApprovalListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_account.ApprovalListPageData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_account.ApproveReq": {
            "type": "object",
            "required": [
                "status",
                "why"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "approve",
                        "reject"
                    ],
                    "example": "approve或者reject"
                },
                "why": {
                    "type": "string",
                    "example": "批准/拒绝用户申请的理由"
                }
            }
        },
        "xinde_internal_dto_account.ApproveResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_account.ListData": {
            "type": "object",
            "properties": {
                "company_name": {
                    "type": "string",
                    "example": "宁波鲍斯产业链服务有限公司"
                },
                "created_at": {
                    "type": "string",
                    "example": "2020-09-08 09:08:09"
                },
                "email": {
                    "type": "string",
                    "example": "13800138000@qq.com"
                },
                "id": {
                    "type": "integer",
                    "example": 2
                },
                "name": {
                    "type": "string",
                    "example": "张三，真实名称"
                },
                "phone": {
                    "type": "string",
                    "example": "13800138000"
                },
                "price_level": {
                    "type": "string",
                    "example": "price_1"
                },
                "recent_search_at": {
                    "type": "string",
                    "example": "2020-09-08 09:08:09"
                },
                "remark": {
                    "type": "string",
                    "example": "备注"
                },
                "role": {
                    "type": "string",
                    "example": "普通用户"
                },
                "search_device": {
                    "type": "string",
                    "example": "车削刀杆"
                },
                "username": {
                    "type": "string",
                    "example": "张三，账号名称"
                }
            }
        },
        "xinde_internal_dto_account.ListPageData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xinde_internal_dto_account.ListData"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "pages": {
                    "type": "integer",
                    "example": 7
                },
                "total": {
                    "type": "integer",
                    "example": 137
                }
            }
        },
        "xinde_internal_dto_account.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_account.ListPageData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_account.LoginData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "jwt_token"
                },
                "email": {
                    "type": "string",
                    "example": "1921771473@qq.com"
                },
                "name": {
                    "type": "string",
                    "example": "金晖"
                },
                "phone": {
                    "type": "string",
                    "example": "13065859690"
                },
                "username": {
                    "type": "string",
                    "example": "金晖"
                }
            }
        },
        "xinde_internal_dto_account.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "923845797582"
                },
                "username": {
                    "type": "string",
                    "example": "金晖"
                }
            }
        },
        "xinde_internal_dto_account.LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_account.LoginData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_account.RegisterReq": {
            "type": "object",
            "required": [
                "company_name",
                "confirmed_password",
                "name",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "company_address": {
                    "type": "string",
                    "example": "浙江省宁波市奉化区江口街道聚潮路55号，可选"
                },
                "company_name": {
                    "type": "string",
                    "example": "宁波鲍斯产业链服务有限公司"
                },
                "confirmed_password": {
                    "type": "string",
                    "example": "923845797582"
                },
                "email": {
                    "type": "string",
                    "example": "1921771473@qq.com，可选"
                },
                "name": {
                    "type": "string",
                    "example": "金晖，真实姓名"
                },
                "password": {
                    "type": "string",
                    "example": "923845797582"
                },
                "phone": {
                    "type": "string",
                    "example": "13065859690"
                },
                "username": {
                    "type": "string",
                    "example": "金晖，账号名称"
                }
            }
        },
        "xinde_internal_dto_account.RegisterResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_account.ResetRemarkReq": {
            "type": "object",
            "properties": {
                "remark": {
                    "type": "string",
                    "example": "这是一条备注"
                }
            }
        },
        "xinde_internal_dto_account.UpdatePasswordReq": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "这是一个密码"
                }
            }
        },
        "xinde_internal_dto_attachment.ListData": {
            "type": "object",
            "properties": {
                "business_type": {
                    "type": "string",
                    "example": "price_import"
                },
                "created_at": {
                    "type": "string"
                },
                "file_size": {
                    "type": "string",
                    "example": "1.2MB"
                },
                "file_type": {
                    "type": "string",
                    "example": "xxxxyyyzzz.xlsx"
                },
                "filename": {
                    "type": "string",
                    "example": "价格表"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "storage_driver": {
                    "type": "string",
                    "example": "local或oss或其他"
                },
                "uploaded_by": {
                    "description": "显示上传者用户名，而不是ID",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "xinde_internal_dto_attachment.ListPageData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xinde_internal_dto_attachment.ListData"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "pages": {
                    "type": "integer",
                    "example": 7
                },
                "total": {
                    "type": "integer",
                    "example": 137
                }
            }
        },
        "xinde_internal_dto_attachment.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_attachment.ListPageData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_company.ListData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "浙江省宁波市奉化区江口街道聚潮路55号"
                },
                "created_at": {
                    "type": "string",
                    "example": "2021-09-09 09:09:09"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "宁波鲍斯产业链有限公司"
                },
                "price_level": {
                    "type": "string",
                    "example": "折扣等级1 折扣等级2 折扣等级3 折扣等级4"
                }
            }
        },
        "xinde_internal_dto_company.ListPageData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xinde_internal_dto_company.ListData"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "pages": {
                    "type": "integer",
                    "example": 7
                },
                "total": {
                    "type": "integer",
                    "example": 137
                }
            }
        },
        "xinde_internal_dto_company.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_company.ListPageData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_company.UpdatePriceLevelReq": {
            "type": "object",
            "required": [
                "price_level"
            ],
            "properties": {
                "price_level": {
                    "type": "string",
                    "enum": [
                        "price_1",
                        "price_2",
                        "price_3",
                        "price_4"
                    ],
                    "example": "price_1或price_2或price_3或price_4"
                }
            }
        },
        "xinde_internal_dto_price.ListData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "price_1": {
                    "type": "number",
                    "example": 1571.3
                },
                "price_2": {
                    "type": "number",
                    "example": 1445.6
                },
                "price_3": {
                    "type": "number",
                    "example": 1230
                },
                "price_4": {
                    "type": "number",
                    "example": 1127
                },
                "product_code": {
                    "type": "string",
                    "example": "WGC001547"
                },
                "spec_code": {
                    "type": "string",
                    "example": "SDQCR1212H07"
                },
                "unit": {
                    "type": "string",
                    "example": "PCS"
                }
            }
        },
        "xinde_internal_dto_price.ListPageData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xinde_internal_dto_price.ListData"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 20
                },
                "pages": {
                    "type": "integer",
                    "example": 7
                },
                "total": {
                    "type": "integer",
                    "example": 137
                }
            }
        },
        "xinde_internal_dto_price.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_price.ListPageData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据，空时不返回该字段"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "xinde API",
	Description:      "This is a sample server for xinde.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
