// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account/login": {
            "post": {
                "description": "用户登录，返回JWT token和用户基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.LoginResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/xinde_pkg_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/account/register": {
            "post": {
                "description": "用户名，真实姓名，公司名称，公司地址（可选），密码，手机号，邮箱（可选）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "注册一个新用户",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/xinde_internal_dto_account.RegisterResp"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "xinde_internal_dto_account.LoginData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "jwt_token"
                },
                "email": {
                    "type": "string",
                    "example": "1921771473@qq.com"
                },
                "name": {
                    "type": "string",
                    "example": "金晖"
                },
                "phone": {
                    "type": "string",
                    "example": "13065859690"
                },
                "username": {
                    "type": "string",
                    "example": "金晖"
                }
            }
        },
        "xinde_internal_dto_account.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "923845797582"
                },
                "username": {
                    "type": "string",
                    "example": "金晖"
                }
            }
        },
        "xinde_internal_dto_account.LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/xinde_internal_dto_account.LoginData"
                },
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_internal_dto_account.RegisterReq": {
            "type": "object",
            "required": [
                "company_name",
                "confirmed_password",
                "name",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "company_address": {
                    "type": "string",
                    "example": "浙江省宁波市奉化区江口街道聚潮路55号"
                },
                "company_name": {
                    "type": "string",
                    "example": "宁波鲍斯产业链服务有限公司"
                },
                "confirmed_password": {
                    "type": "string",
                    "example": "923845797582"
                },
                "email": {
                    "type": "string",
                    "example": "1921771473@qq.com"
                },
                "name": {
                    "type": "string",
                    "example": "金晖"
                },
                "password": {
                    "type": "string",
                    "example": "923845797582"
                },
                "phone": {
                    "type": "string",
                    "example": "13065859690"
                },
                "username": {
                    "type": "string",
                    "example": "金晖"
                }
            }
        },
        "xinde_internal_dto_account.RegisterResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "操作成功"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "xinde_pkg_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据，空时不返回该字段"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "xinde API",
	Description:      "This is a sample server for xinde.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
