basePath: /api/v1
definitions:
  xinde_internal_model_dto_account.RegisterReq:
    properties:
      company_address:
        type: string
      company_name:
        type: string
      confirmed_password:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - company_name
    - confirmed_password
    - name
    - password
    - phone
    - username
    type: object
  xinde_internal_model_dto_account.RegisterResp:
    properties:
      msg:
        type: string
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for xinde.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: xinde API
  version: "1.0"
paths:
  /api/v1/account/register:
    post:
      consumes:
      - application/json
      description: 用户名，真实姓名，公司名称，公司地址（可选），密码，手机号，邮箱（可选）
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/xinde_internal_model_dto_account.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            $ref: '#/definitions/xinde_internal_model_dto_account.RegisterResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/xinde_internal_model_dto_account.RegisterResp'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/xinde_internal_model_dto_account.RegisterResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/xinde_internal_model_dto_account.RegisterResp'
      summary: 注册一个新用户
      tags:
      - Account
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Ping server
      tags:
      - health
swagger: "2.0"
